from . import data_creation_and_loader

from .data_creation_and_loader import get_exercise_1_and_5_dataset
from .data_creation_and_loader import get_exercise_2_dataset
from .data_creation_and_loader import get_exercise_3_dataframe
from .data_creation_and_loader import get_exercise_4_list

from .data_creation_and_loader import create_datasets
